
-------------------------------------------------------------------------------------
---------------------------------  PH-1621 -------------------------------------------
--------------------------------------------------------------------------------------


 ALTER TABLE PROC_RFA_EVALUATOR_USER ADD EVALUATOR_SUMMARY_TMP VARCHAR(MAX);
UPDATE PROC_RFA_EVALUATOR_USER SET EVALUATOR_SUMMARY_TMP=EVALUATOR_SUMMARY;
COMMIT ;
ALTER TABLE PROC_RFA_EVALUATOR_USER DROP COLUMN EVALUATOR_SUMMARY;
sp_rename 'PROC_RFA_EVALUATOR_USER.EVALUATOR_SUMMARY_TMP', 'EVALUATOR_SUMMARY', 'COLUMN';


ALTER TABLE PROC_RFI_EVALUATOR_USER ADD EVALUATOR_SUMMARY_TMP VARCHAR(MAX);
UPDATE PROC_RFI_EVALUATOR_USER SET EVALUATOR_SUMMARY_TMP=EVALUATOR_SUMMARY;
COMMIT;
ALTER TABLE PROC_RFI_EVALUATOR_USER DROP COLUMN EVALUATOR_SUMMARY;
sp_rename 'PROC_RFI_EVALUATOR_USER.EVALUATOR_SUMMARY_TMP', 'EVALUATOR_SUMMARY', 'COLUMN';


ALTER TABLE PROC_RFP_EVALUATOR_USER ADD EVALUATOR_SUMMARY_TMP VARCHAR(MAX);
UPDATE PROC_RFP_EVALUATOR_USER SET EVALUATOR_SUMMARY_TMP=EVALUATOR_SUMMARY;
COMMIT;
ALTER TABLE PROC_RFP_EVALUATOR_USER DROP COLUMN EVALUATOR_SUMMARY;
sp_rename 'PROC_RFP_EVALUATOR_USER.EVALUATOR_SUMMARY_TMP', 'EVALUATOR_SUMMARY', 'COLUMN';


ALTER TABLE PROC_RFQ_EVALUATOR_USER ADD EVALUATOR_SUMMARY_TMP VARCHAR(MAX);
UPDATE PROC_RFQ_EVALUATOR_USER SET EVALUATOR_SUMMARY_TMP=EVALUATOR_SUMMARY;
COMMIT;
ALTER TABLE PROC_RFQ_EVALUATOR_USER DROP COLUMN EVALUATOR_SUMMARY;
sp_rename 'PROC_RFQ_EVALUATOR_USER.EVALUATOR_SUMMARY_TMP', 'EVALUATOR_SUMMARY', 'COLUMN';


ALTER TABLE PROC_RFT_EVALUATOR_USER ADD EVALUATOR_SUMMARY_TMP VARCHAR(MAX);
UPDATE PROC_RFT_EVALUATOR_USER SET EVALUATOR_SUMMARY_TMP=EVALUATOR_SUMMARY;
COMMIT;
ALTER TABLE PROC_RFT_EVALUATOR_USER DROP COLUMN EVALUATOR_SUMMARY;
sp_rename 'PROC_RFT_EVALUATOR_USER.EVALUATOR_SUMMARY_TMP', 'EVALUATOR_SUMMARY', 'COLUMN';


-- Envelop

ALTER TABLE PROC_RFA_ENVELOP ADD LEAD_EVALUATOR_SUMMARY_TMP VARCHAR(MAX);
UPDATE PROC_RFA_ENVELOP SET LEAD_EVALUATOR_SUMMARY_TMP=LEAD_EVALUATOR_SUMMARY;
COMMIT ;
ALTER TABLE PROC_RFA_ENVELOP DROP COLUMN LEAD_EVALUATOR_SUMMARY;
sp_rename 'PROC_RFA_ENVELOP.LEAD_EVALUATOR_SUMMARY_TMP', 'LEAD_EVALUATOR_SUMMARY', 'COLUMN';


ALTER TABLE PROC_RFI_ENVELOP ADD LEAD_EVALUATOR_SUMMARY_TMP VARCHAR(MAX);
UPDATE PROC_RFI_ENVELOP SET LEAD_EVALUATOR_SUMMARY_TMP=LEAD_EVALUATOR_SUMMARY;
COMMIT ;
ALTER TABLE PROC_RFI_ENVELOP DROP COLUMN LEAD_EVALUATOR_SUMMARY;
sp_rename 'PROC_RFI_ENVELOP.LEAD_EVALUATOR_SUMMARY_TMP', 'LEAD_EVALUATOR_SUMMARY', 'COLUMN';


ALTER TABLE PROC_RFP_ENVELOP ADD LEAD_EVALUATOR_SUMMARY_TMP VARCHAR(MAX);
UPDATE PROC_RFP_ENVELOP SET LEAD_EVALUATOR_SUMMARY_TMP=LEAD_EVALUATOR_SUMMARY;
COMMIT ;
ALTER TABLE PROC_RFP_ENVELOP DROP COLUMN LEAD_EVALUATOR_SUMMARY;
sp_rename 'PROC_RFP_ENVELOP.LEAD_EVALUATOR_SUMMARY_TMP', 'LEAD_EVALUATOR_SUMMARY', 'COLUMN';


ALTER TABLE PROC_RFQ_ENVELOP ADD LEAD_EVALUATOR_SUMMARY_TMP VARCHAR(MAX);
UPDATE PROC_RFQ_ENVELOP SET LEAD_EVALUATOR_SUMMARY_TMP=LEAD_EVALUATOR_SUMMARY;
COMMIT ;
ALTER TABLE PROC_RFQ_ENVELOP DROP COLUMN LEAD_EVALUATOR_SUMMARY;
sp_rename 'PROC_RFQ_ENVELOP.LEAD_EVALUATOR_SUMMARY_TMP', 'LEAD_EVALUATOR_SUMMARY', 'COLUMN';


ALTER TABLE PROC_RFT_ENVELOP ADD LEAD_EVALUATOR_SUMMARY_TMP VARCHAR(MAX);
UPDATE PROC_RFT_ENVELOP SET LEAD_EVALUATOR_SUMMARY_TMP=LEAD_EVALUATOR_SUMMARY;
COMMIT ;
ALTER TABLE PROC_RFT_ENVELOP DROP COLUMN LEAD_EVALUATOR_SUMMARY;
sp_rename 'PROC_RFT_ENVELOP.LEAD_EVALUATOR_SUMMARY_TMP', 'LEAD_EVALUATOR_SUMMARY', 'COLUMN';

