/**
 * 
 */
package com.privasia.procurehere.core.enums;

/**
 * @author Ravi
 */
public enum AuditTypes {
	CREATE ("CREATE"), UPDATE ("UPDATE"), DELETE("DELETE"),REQUEST("REQUEST"), ACCEPTED("ACCEPTED"), APPROVED("APPROVED"), AWARD("AWARD"), CANCELLED("CANCELLED"), CONCLUDE("CONCLUDE"), COMPLETE("COMPLETE"), 
	DISQUALIFIED("DISQUALIFIED"), DOWNLOAD("DOWNLOAD"), EVALUATE("EVALUATE"), EXTENSION("EXTENSION"), FINISH("FINISH"), OPEN("OPEN"), ORDERED("ORDERED"), RECEIVED("RECEIVED"), REJECTED("REJECTED"), 
	REMARK("REMARK"), RESUME("RESUME"), SUSPEND("SUSPEND"), VIEW("VIEW"), DECLINED("DECLINED"), ACTIVE("ACTIVE"), INACTIVE("INACTIVE"), BLACKLIST("BLACKLIST"),TRANSFERRED("TRANSFERRED"), SUSPEND_REJECT("SUSPEND REJECT"), 
	SUSPEND_APPROVE("SUSPEND APPROVE"), REQUALIFIED("REQUALIFIED"), REVISED("REVISED"), ASSIGNED("ASSIGNED"), CLOSED("CLOSED"), REVIEW("REVIEW"), AWARD_APPROVE("AWARD APPROVE"), AWARD_REJECT("AWARD REJECT"), DISCARD("DISCARD"),
	TERMINATED("TERMINATED"), CONCLUDEAWARD("CONCLUDE AWARD"), SUSPENDED("SUSPENDED"), DRAFT("DRAFT"), READY("READY");
	
	private String value ;

	private AuditTypes(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	} 
	
	
}
