package com.privasia.procurehere.core.enums;

/**
 * @author parveen
 */
public enum PrTemplateFieldName {
	PR_NAME, REQUESTER, CORRESPONDENCE_ADDRESS, BASE_CURRENCY, DECIMAL, AVAILABLE_BUDGET, COST_CENTER, BUSINESS_UNIT, PAYMENT_TERM, TERM_AND_CONDITION,
	HIDE_OPEN_SUPPLIER,CONTRACT_ITEMS_ONLY, CONVERSION_RATE;
}
