/**
 * 
 */
package com.privasia.procurehere.core.enums;

/**
 * @author Nitin Otageri
 */
public enum RfxTemplateFieldName {
	EVENT_NAME, EVENT_CATEGORY, BASE_CURRENCY, DECIMAL, COST_CENTER, BUSINESS_UNIT, BUDGET_AMOUNT, HISTORIC_AMOUNT, PAYMENT_TERM,PARTICIPATION_FEES,PARTICIPATION_FEE_CURRENCY,DEPOSIT,DEPOSIT_CURRENCY, PRE_BID_BY, PRE_SUPPLIER_PROVIDE_HIGHER,
	PRE_SUPPLIER_SAME_BID, BIDDING_TYPE, IS_BID_INCR_OWN_PREVIOUS, BID_INCR_OWN_PRE_TYPE, BID_INCR_OWN_PRE_VAL, IS_BID_HIGHER_LEADING, BID_HIGHER_LEAD_TYPE,
	BID_HIGHER_LEAD_VAL, START_GATE, AUCTION_PRICE_TYPE, AUCTION_RANK_TYPE, AUCTION_SUPPLIER_TYPE, TIME_EXT_TYPE, TIME_EXT_DURATION, TIME_EXT_DURATION_TYPE, TIME_TRIGGER_TYPE,
	TIME_TRIGGER_VAL, EXTENSION_COUNT, IS_AUTO_BIDDER_DISQUALIFY,BIDDER_DISQUALIFY_COUNT,IS_BIDDING_SAMEPRICE_SUPPLIER ,_UNKNOWN
	,AUCTION_BUY_PRICE_TYPE, AUCTION_BUY_RANK_TYPE, AUCTION_BUY_SUPPLIER_TYPE, EXPECTED_TENDER_STARTEND_DATTIME, FEE_STARTEND_DATETIME, MINIMUM_SUPPLIER_RATING, MAXIMUM_SUPPLIER_RATING,EVALUATION_PROCESS_DECLARATION,SUPPLIER_ACCEPTANCE_DECLARATION
	,PRE_AS_FIRSTBID, SUB_VALIDITY_DAYS, DISABLE_TOTAL_AMOUNT, ESTIMATED_BUDGET,PROCUREMENT_METHOD, PROCUREMENT_CATEGORY, GROUP_CODE,PRE_SET_SAME_PRE_BID_ALL_SUPPLIER;
}
