package com.privasia.procurehere.core.dao.impl;

import java.util.List;

import javax.annotation.Resource;
import javax.persistence.Query;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.context.MessageSource;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import com.privasia.procurehere.core.dao.EmailSettingsDao;
import com.privasia.procurehere.core.entity.EmailSettings;
import com.privasia.procurehere.core.utils.CollectionUtil;

/**
 * @author Ravi
 */
@Repository("emailSettingsDao")
public class EmailSettingsDaoImpl extends GenericDaoImpl<EmailSettings, String> implements EmailSettingsDao {

	private static Logger LOG = LogManager.getLogger(EmailSettingsDaoImpl.class);

	@Resource
	MessageSource messageSource;

	@SuppressWarnings("unchecked")
	@Override
	public EmailSettings loadEmailSettings() {
		final Query query = getEntityManager().createQuery("from EmailSettings e");
		List<EmailSettings> list = query.getResultList();
		return (CollectionUtil.isNotEmpty(list) ? list.get(0) : null);
	}

	@Override
	@Transactional(readOnly = false, propagation = Propagation.REQUIRES_NEW)
	public void createViewForDashboard() {
		Query query;
		try {
			String view = "CREATE OR REPLACE VIEW PROC_RFX_EVENT_DETAILS AS ";
			view += " select distinct a.ID, a.EVENT_NAME, a.TENANT_ID, a.STATUS, a.CREATED_DATE, puser.LOGIN_ID as CREATED_BY, a.MODIFIED_DATE, a.EVENT_TYPE, a.EVENT_START, a.EVENT_END, a.REFERANCE_NUMBER, a.BUSINESS_UNIT_NAME, a.EVENT_ID, puser.USER_NAME as EVENT_USER from (";
			view += " SELECT e.ID, e.EVENT_ID, e.EVENT_NAME, e.TENANT_ID, e.STATUS, e.ACTION_DATE, e.ACTION_BY, e.EVENT_START, e.EVENT_END, e.MODIFIED_DATE, e.BUSINESS_UNIT_ID, e.CREATED_DATE, e.CREATED_BY, e.REFERANCE_NUMBER, e.EVENT_OWNER, bu.BUSINESS_UNIT_NAME, 'Request for Information' as EVENT_TYPE FROM PROC_RFI_EVENTS e left outer join PROC_BUSINESS_UNIT bu on e.BUSINESS_UNIT_ID = bu.ID";
			view += " UNION ";
			view += " SELECT e.ID, e.EVENT_ID, e.EVENT_NAME, e.TENANT_ID, e.STATUS, e.ACTION_DATE, e.ACTION_BY, e.EVENT_START, e.EVENT_END, e.MODIFIED_DATE, e.BUSINESS_UNIT_ID, e.CREATED_DATE, e.CREATED_BY, e.REFERANCE_NUMBER, e.EVENT_OWNER, bu.BUSINESS_UNIT_NAME, 'Request for Tender' as EVENT_TYPE FROM PROC_RFT_EVENTS e left outer join PROC_BUSINESS_UNIT bu on e.BUSINESS_UNIT_ID = bu.ID";
			view += " UNION ";
			view += " SELECT e.ID, e.EVENT_ID, e.EVENT_NAME, e.TENANT_ID, e.STATUS, e.ACTION_DATE, e.ACTION_BY, e.EVENT_START, e.EVENT_END, e.MODIFIED_DATE, e.BUSINESS_UNIT_ID, e.CREATED_DATE, e.CREATED_BY, e.REFERANCE_NUMBER, e.EVENT_OWNER, bu.BUSINESS_UNIT_NAME, 'Request for Proposal' as EVENT_TYPE FROM PROC_RFP_EVENTS e left outer join PROC_BUSINESS_UNIT bu on e.BUSINESS_UNIT_ID = bu.ID";
			view += " UNION ";
			view += " SELECT e.ID, e.EVENT_ID, e.EVENT_NAME, e.TENANT_ID, e.STATUS, e.ACTION_DATE, e.ACTION_BY, e.EVENT_START, e.EVENT_END, e.MODIFIED_DATE, e.BUSINESS_UNIT_ID, e.CREATED_DATE, e.CREATED_BY, e.REFERANCE_NUMBER, e.EVENT_OWNER, bu.BUSINESS_UNIT_NAME, 'Request for Quotation' as EVENT_TYPE FROM PROC_RFQ_EVENTS e left outer join PROC_BUSINESS_UNIT bu on e.BUSINESS_UNIT_ID = bu.ID";
			view += " UNION ";
			view += " SELECT e.ID, e.EVENT_ID, e.EVENT_NAME, e.TENANT_ID, e.STATUS, e.ACTION_DATE, e.ACTION_BY, e.EVENT_START, e.EVENT_END, e.MODIFIED_DATE, e.BUSINESS_UNIT_ID, e.CREATED_DATE, e.CREATED_BY, e.REFERANCE_NUMBER, e.EVENT_OWNER, bu.BUSINESS_UNIT_NAME, 'Request for Auction' as EVENT_TYPE FROM PROC_RFA_EVENTS e left outer join PROC_BUSINESS_UNIT bu on e.BUSINESS_UNIT_ID = bu.ID";
			view += " ) a , PROC_USER puser where a.CREATED_BY = puser.ID ";
			query = getEntityManager().createNativeQuery(view);
			query.executeUpdate();
		} catch (Exception e) {
			LOG.error("Error creating RfxEventDetailsView : " + e.getMessage(), e);
		}
	}

	@Override
	@Transactional(readOnly = false, propagation = Propagation.REQUIRES_NEW)
	public void createViews() {
		Query query;
		try {
			String view = "CREATE OR REPLACE VIEW PROC_RFX_EVENTS AS ";
			view += " SELECT e.ID,e.CONCLUDE_BY, e.IS_ERP_ENABLE, e.DELIVERY_DATE,e.CONCLUDE_DATE, e.URGENT_EVENT, e.START_MESSAGE_SENT, e.SUSPEND_REMARKS, e.CANCEL_REASON, e.PREVIOUS_EVENT, e.NEXT_EVENT, e.PREVIOUS_EVENT_TYPE, e.NEXT_EVENT_TYPE, e.CONCLUDE_REMARKS, e.IS_BILLOFQUANTITY_REQ, e.BUDGET_AMOUNT, e.CREATED_DATE, e.BUYER_SET_DECIMAL, e.IS_DOCUMENT_REQ, e.EVENT_DESCRIPTION, e.EVENT_END, e.EVENT_ID, e.EVENT_NAME, e.EVENT_PUBLISH_DATE, e.EVENT_START, e.EVENT_VISIBILITY, e.HISTORICAL_AMOUNT, e.IS_MEETINGS_REQ, e.MODIFIED_DATE, e.PARTICIPATION_FEES, e.PAYMENT_TERM, e.IS_QUESTIONNAIRES_REQ, e.REFERANCE_NUMBER, e.STATUS, e.SUBMISSION_VALIDITY_DAYS, e.TENANT_ID, e.CURRENCY_ID, e.COST_CENTER, e.BUSINESS_UNIT_ID, e.CREATED_BY, e.DELIVERY_ADDRESS, e.EVENT_OWNER, e.EVENT_CATEGORY, e.MODIFIED_BY, e.PARTICIPATION_FEE_CURRENCY, e.TEMPLATE_ID, e.IS_BQ_COMPLETED, e.IS_CQ_COMPLETED, e.IS_DOCUMENT_COMPLETED, e.IS_ENVELOP_COMPLETED, e.IS_EVENT_DETAIL_COMPLETED, e.IS_MEETINGS_COMPLETED, e.IS_SUMMARY_COMPLETED, e.IS_SUPPLIER_COMPLETED, e.ACTION_DATE, e.ACTION_BY, s.SUPPLIER_ID, s.IS_BID_SUBMITTED, s.SUPPLIER_EVENT_READ_TIME, s.SUPPLIER_INVITED_TIME, s.SUPPLIER_BID_SUBMITTED_TIME, s.SUBMISSION_STATUS, e.SUSPENSION_TYPE, 'Request for Information' as EVENT_TYPE ,e.IS_AWARDED ,e.ERP_DOC_NO ,e.VIEW_SUPPLIER_NAME,e.ALLOW_CLOSE_ENVELOPE,e.ALLOW_ADD_SUPPLIER,e.ALLOW_TO_SUSPEND_EVENT,e.PREVIOUS_REQUEST,e.DEPOSIT,e.DEPOSIT_CURRENCY,e.DISABLE_MASKING,e.UNMASKED_BY,e.INTERNAL_REMARKS,e.MINIMUM_SUPPLIER_RATING,e.MAXIMUM_SUPPLIER_RATING,e.EVENT_PUSH_DATE,e.AWARD_DATE  FROM PROC_RFI_EVENTS e left outer join PROC_RFI_EVENT_SUPPLIERS s on e.ID = s.EVENT_ID ";
			view += " UNION ";
			view += " SELECT e.ID,e.CONCLUDE_BY, e.IS_ERP_ENABLE, e.DELIVERY_DATE,e.CONCLUDE_DATE, e.URGENT_EVENT, e.START_MESSAGE_SENT, e.SUSPEND_REMARKS, e.CANCEL_REASON, e.PREVIOUS_EVENT, e.NEXT_EVENT, e.PREVIOUS_EVENT_TYPE, e.NEXT_EVENT_TYPE, e.CONCLUDE_REMARKS, e.IS_BILLOFQUANTITY_REQ, e.BUDGET_AMOUNT, e.CREATED_DATE, e.BUYER_SET_DECIMAL, e.IS_DOCUMENT_REQ, e.EVENT_DESCRIPTION, e.EVENT_END, e.EVENT_ID, e.EVENT_NAME, e.EVENT_PUBLISH_DATE, e.EVENT_START, e.EVENT_VISIBILITY, e.HISTORICAL_AMOUNT, e.IS_MEETINGS_REQ, e.MODIFIED_DATE, e.PARTICIPATION_FEES, e.PAYMENT_TERM, e.IS_QUESTIONNAIRES_REQ, e.REFERANCE_NUMBER, e.STATUS, e.SUBMISSION_VALIDITY_DAYS, e.TENANT_ID, e.CURRENCY_ID, e.COST_CENTER, e.BUSINESS_UNIT_ID, e.CREATED_BY, e.DELIVERY_ADDRESS, e.EVENT_OWNER, e.EVENT_CATEGORY, e.MODIFIED_BY, e.PARTICIPATION_FEE_CURRENCY, e.TEMPLATE_ID, e.IS_BQ_COMPLETED, e.IS_CQ_COMPLETED, e.IS_DOCUMENT_COMPLETED, e.IS_ENVELOP_COMPLETED, e.IS_EVENT_DETAIL_COMPLETED, e.IS_MEETINGS_COMPLETED, e.IS_SUMMARY_COMPLETED, e.IS_SUPPLIER_COMPLETED, e.ACTION_DATE, e.ACTION_BY, s.SUPPLIER_ID, s.IS_BID_SUBMITTED, s.SUPPLIER_EVENT_READ_TIME, s.SUPPLIER_INVITED_TIME, s.SUPPLIER_BID_SUBMITTED_TIME, s.SUBMISSION_STATUS, e.SUSPENSION_TYPE, 'Request for Tender' as EVENT_TYPE ,e.IS_AWARDED ,e.ERP_DOC_NO ,e.VIEW_SUPPLIER_NAME,e.ALLOW_CLOSE_ENVELOPE,e.ALLOW_ADD_SUPPLIER,e.ALLOW_TO_SUSPEND_EVENT,e.PREVIOUS_REQUEST,e.DEPOSIT,e.DEPOSIT_CURRENCY,e.DISABLE_MASKING,e.UNMASKED_BY,e.INTERNAL_REMARKS,e.MINIMUM_SUPPLIER_RATING,e.MAXIMUM_SUPPLIER_RATING,e.EVENT_PUSH_DATE,e.AWARD_DATE   FROM PROC_RFT_EVENTS e left outer join PROC_RFT_EVENT_SUPPLIERS s on e.ID = s.EVENT_ID ";
			view += " UNION ";
			view += " SELECT e.ID,e.CONCLUDE_BY, e.IS_ERP_ENABLE, e.DELIVERY_DATE,e.CONCLUDE_DATE, e.URGENT_EVENT, e.START_MESSAGE_SENT, e.SUSPEND_REMARKS, e.CANCEL_REASON, e.PREVIOUS_EVENT, e.NEXT_EVENT, e.PREVIOUS_EVENT_TYPE, e.NEXT_EVENT_TYPE, e.CONCLUDE_REMARKS, e.IS_BILLOFQUANTITY_REQ, e.BUDGET_AMOUNT, e.CREATED_DATE, e.BUYER_SET_DECIMAL, e.IS_DOCUMENT_REQ, e.EVENT_DESCRIPTION, e.EVENT_END, e.EVENT_ID, e.EVENT_NAME, e.EVENT_PUBLISH_DATE, e.EVENT_START, e.EVENT_VISIBILITY, e.HISTORICAL_AMOUNT, e.IS_MEETINGS_REQ, e.MODIFIED_DATE, e.PARTICIPATION_FEES, e.PAYMENT_TERM, e.IS_QUESTIONNAIRES_REQ, e.REFERANCE_NUMBER, e.STATUS, e.SUBMISSION_VALIDITY_DAYS, e.TENANT_ID, e.CURRENCY_ID, e.COST_CENTER, e.BUSINESS_UNIT_ID, e.CREATED_BY, e.DELIVERY_ADDRESS, e.EVENT_OWNER, e.EVENT_CATEGORY, e.MODIFIED_BY, e.PARTICIPATION_FEE_CURRENCY, e.TEMPLATE_ID, e.IS_BQ_COMPLETED, e.IS_CQ_COMPLETED, e.IS_DOCUMENT_COMPLETED, e.IS_ENVELOP_COMPLETED, e.IS_EVENT_DETAIL_COMPLETED, e.IS_MEETINGS_COMPLETED, e.IS_SUMMARY_COMPLETED, e.IS_SUPPLIER_COMPLETED, e.ACTION_DATE, e.ACTION_BY, s.SUPPLIER_ID, s.IS_BID_SUBMITTED, s.SUPPLIER_EVENT_READ_TIME, s.SUPPLIER_INVITED_TIME, s.SUPPLIER_BID_SUBMITTED_TIME, s.SUBMISSION_STATUS, e.SUSPENSION_TYPE, 'Request for Proposal' as EVENT_TYPE ,e.IS_AWARDED ,e.ERP_DOC_NO ,e.VIEW_SUPPLIER_NAME,e.ALLOW_CLOSE_ENVELOPE,e.ALLOW_ADD_SUPPLIER,e.ALLOW_TO_SUSPEND_EVENT,e.PREVIOUS_REQUEST,e.DEPOSIT,e.DEPOSIT_CURRENCY,e.DISABLE_MASKING ,e.UNMASKED_BY,e.INTERNAL_REMARKS,e.MINIMUM_SUPPLIER_RATING,e.MAXIMUM_SUPPLIER_RATING,e.EVENT_PUSH_DATE,e.AWARD_DATE  FROM PROC_RFP_EVENTS e left outer join PROC_RFP_EVENT_SUPPLIERS s on e.ID = s.EVENT_ID ";
			view += " UNION ";
			view += " SELECT e.ID,e.CONCLUDE_BY, e.IS_ERP_ENABLE, e.DELIVERY_DATE,e.CONCLUDE_DATE, e.URGENT_EVENT, e.START_MESSAGE_SENT, e.SUSPEND_REMARKS, e.CANCEL_REASON, e.PREVIOUS_EVENT, e.NEXT_EVENT, e.PREVIOUS_EVENT_TYPE, e.NEXT_EVENT_TYPE, e.CONCLUDE_REMARKS, e.IS_BILLOFQUANTITY_REQ, e.BUDGET_AMOUNT, e.CREATED_DATE, e.BUYER_SET_DECIMAL, e.IS_DOCUMENT_REQ, e.EVENT_DESCRIPTION, e.EVENT_END, e.EVENT_ID, e.EVENT_NAME, e.EVENT_PUBLISH_DATE, e.EVENT_START, e.EVENT_VISIBILITY, e.HISTORICAL_AMOUNT, e.IS_MEETINGS_REQ, e.MODIFIED_DATE, e.PARTICIPATION_FEES, e.PAYMENT_TERM, e.IS_QUESTIONNAIRES_REQ, e.REFERANCE_NUMBER, e.STATUS, e.SUBMISSION_VALIDITY_DAYS, e.TENANT_ID, e.CURRENCY_ID, e.COST_CENTER, e.BUSINESS_UNIT_ID, e.CREATED_BY, e.DELIVERY_ADDRESS, e.EVENT_OWNER, e.EVENT_CATEGORY, e.MODIFIED_BY, e.PARTICIPATION_FEE_CURRENCY, e.TEMPLATE_ID, e.IS_BQ_COMPLETED, e.IS_CQ_COMPLETED, e.IS_DOCUMENT_COMPLETED, e.IS_ENVELOP_COMPLETED, e.IS_EVENT_DETAIL_COMPLETED, e.IS_MEETINGS_COMPLETED, e.IS_SUMMARY_COMPLETED, e.IS_SUPPLIER_COMPLETED, e.ACTION_DATE, e.ACTION_BY, s.SUPPLIER_ID, s.IS_BID_SUBMITTED, s.SUPPLIER_EVENT_READ_TIME, s.SUPPLIER_INVITED_TIME, s.SUPPLIER_BID_SUBMITTED_TIME, s.SUBMISSION_STATUS, e.SUSPENSION_TYPE, 'Request for Quotation' as EVENT_TYPE,e.IS_AWARDED ,e.ERP_DOC_NO ,e.VIEW_SUPPLIER_NAME,e.ALLOW_CLOSE_ENVELOPE,e.ALLOW_ADD_SUPPLIER,e.ALLOW_TO_SUSPEND_EVENT,e.PREVIOUS_REQUEST,e.DEPOSIT,e.DEPOSIT_CURRENCY,e.DISABLE_MASKING ,e.UNMASKED_BY,e.INTERNAL_REMARKS,e.MINIMUM_SUPPLIER_RATING,e.MAXIMUM_SUPPLIER_RATING,e.EVENT_PUSH_DATE,e.AWARD_DATE  FROM PROC_RFQ_EVENTS e left outer join PROC_RFQ_EVENT_SUPPLIERS s on e.ID = s.EVENT_ID ";
			view += " UNION ";
			view += " SELECT e.ID,e.CONCLUDE_BY, e.IS_ERP_ENABLE, e.DELIVERY_DATE,e.CONCLUDE_DATE, e.URGENT_EVENT, e.START_MESSAGE_SENT, e.SUSPEND_REMARKS, e.CANCEL_REASON, e.PREVIOUS_EVENT, e.NEXT_EVENT, e.PREVIOUS_EVENT_TYPE, e.NEXT_EVENT_TYPE, e.CONCLUDE_REMARKS, e.IS_BILLOFQUANTITY_REQ, e.BUDGET_AMOUNT, e.CREATED_DATE, e.BUYER_SET_DECIMAL, e.IS_DOCUMENT_REQ, e.EVENT_DESCRIPTION, e.EVENT_END, e.EVENT_ID, e.EVENT_NAME, e.EVENT_PUBLISH_DATE, e.EVENT_START, e.EVENT_VISIBILITY, e.HISTORICAL_AMOUNT, e.IS_MEETINGS_REQ, e.MODIFIED_DATE, e.PARTICIPATION_FEES, e.PAYMENT_TERM, e.IS_QUESTIONNAIRES_REQ, e.REFERANCE_NUMBER, e.STATUS, e.SUBMISSION_VALIDITY_DAYS, e.TENANT_ID, e.CURRENCY_ID, e.COST_CENTER, e.BUSINESS_UNIT_ID, e.CREATED_BY, e.DELIVERY_ADDRESS, e.EVENT_OWNER, e.EVENT_CATEGORY, e.MODIFIED_BY, e.PARTICIPATION_FEE_CURRENCY, e.TEMPLATE_ID, e.IS_BQ_COMPLETED, e.IS_CQ_COMPLETED, e.IS_DOCUMENT_COMPLETED, e.IS_ENVELOP_COMPLETED, e.IS_EVENT_DETAIL_COMPLETED, e.IS_MEETINGS_COMPLETED, e.IS_SUMMARY_COMPLETED, e.IS_SUPPLIER_COMPLETED, e.ACTION_DATE, e.ACTION_BY, s.SUPPLIER_ID, s.IS_BID_SUBMITTED, s.SUPPLIER_EVENT_READ_TIME, s.SUPPLIER_INVITED_TIME, s.SUPPLIER_BID_SUBMITTED_TIME, s.SUBMISSION_STATUS, e.SUSPENSION_TYPE, 'Request for Auction' as EVENT_TYPE ,e.IS_AWARDED ,e.ERP_DOC_NO ,e.VIEW_SUPPLIER_NAME,e.ALLOW_CLOSE_ENVELOPE,e.ALLOW_ADD_SUPPLIER,e.ALLOW_TO_SUSPEND_EVENT,e.PREVIOUS_REQUEST,e.DEPOSIT,e.DEPOSIT_CURRENCY,e.DISABLE_MASKING,e.UNMASKED_BY,e.INTERNAL_REMARKS,e.MINIMUM_SUPPLIER_RATING,e.MAXIMUM_SUPPLIER_RATING,e.EVENT_PUSH_DATE,e.AWARD_DATE   FROM PROC_RFA_EVENTS e left outer join PROC_RFA_EVENT_SUPPLIERS s on e.ID = s.EVENT_ID ";

			query = getEntityManager().createNativeQuery(view);
			query.executeUpdate();

			
			view = "CREATE OR REPLACE VIEW PROC_RFX_SIMPLE_EVENTS AS ";
			view += "  SELECT e.ID,e.CONCLUDE_BY, e.IS_ERP_ENABLE, e.DELIVERY_DATE,e.CONCLUDE_DATE, e.URGENT_EVENT, e.START_MESSAGE_SENT, e.SUSPEND_REMARKS, e.CANCEL_REASON, e.PREVIOUS_EVENT, e.NEXT_EVENT, e.PREVIOUS_EVENT_TYPE, e.NEXT_EVENT_TYPE, e.CONCLUDE_REMARKS, e.IS_BILLOFQUANTITY_REQ, e.BUDGET_AMOUNT, e.CREATED_DATE, e.BUYER_SET_DECIMAL, e.IS_DOCUMENT_REQ, e.EVENT_DESCRIPTION, e.EVENT_END, e.EVENT_ID, e.EVENT_NAME, e.EVENT_PUBLISH_DATE, e.EVENT_START, e.EVENT_VISIBILITY, e.HISTORICAL_AMOUNT, e.IS_MEETINGS_REQ, e.MODIFIED_DATE, e.PARTICIPATION_FEES, e.PAYMENT_TERM, e.IS_QUESTIONNAIRES_REQ, e.REFERANCE_NUMBER, e.STATUS, e.SUBMISSION_VALIDITY_DAYS, e.TENANT_ID, e.CURRENCY_ID, e.COST_CENTER, e.BUSINESS_UNIT_ID, e.CREATED_BY, e.DELIVERY_ADDRESS, e.EVENT_OWNER, e.EVENT_CATEGORY, e.MODIFIED_BY, e.PARTICIPATION_FEE_CURRENCY, e.TEMPLATE_ID, e.IS_BQ_COMPLETED, e.IS_CQ_COMPLETED, e.IS_DOCUMENT_COMPLETED, e.IS_ENVELOP_COMPLETED, e.IS_EVENT_DETAIL_COMPLETED, e.IS_MEETINGS_COMPLETED, e.IS_SUMMARY_COMPLETED, e.IS_SUPPLIER_COMPLETED, e.ACTION_DATE, e.ACTION_BY,  e.SUSPENSION_TYPE, 'Request for Information' as EVENT_TYPE ,e.IS_AWARDED ,e.ERP_DOC_NO ,e.VIEW_SUPPLIER_NAME,e.ALLOW_CLOSE_ENVELOPE,e.ALLOW_ADD_SUPPLIER,e.ALLOW_TO_SUSPEND_EVENT,e.PREVIOUS_REQUEST,e.DEPOSIT,e.DEPOSIT_CURRENCY,e.DISABLE_MASKING,e.UNMASKED_BY,e.INTERNAL_REMARKS,e.MINIMUM_SUPPLIER_RATING,e.MAXIMUM_SUPPLIER_RATING,e.EVENT_PUSH_DATE,e.AWARD_DATE  FROM PROC_RFI_EVENTS e ";  
			view += " UNION  ";
			view += " SELECT e.ID,e.CONCLUDE_BY, e.IS_ERP_ENABLE, e.DELIVERY_DATE,e.CONCLUDE_DATE, e.URGENT_EVENT, e.START_MESSAGE_SENT, e.SUSPEND_REMARKS, e.CANCEL_REASON, e.PREVIOUS_EVENT, e.NEXT_EVENT, e.PREVIOUS_EVENT_TYPE, e.NEXT_EVENT_TYPE, e.CONCLUDE_REMARKS, e.IS_BILLOFQUANTITY_REQ, e.BUDGET_AMOUNT, e.CREATED_DATE, e.BUYER_SET_DECIMAL, e.IS_DOCUMENT_REQ, e.EVENT_DESCRIPTION, e.EVENT_END, e.EVENT_ID, e.EVENT_NAME, e.EVENT_PUBLISH_DATE, e.EVENT_START, e.EVENT_VISIBILITY, e.HISTORICAL_AMOUNT, e.IS_MEETINGS_REQ, e.MODIFIED_DATE, e.PARTICIPATION_FEES, e.PAYMENT_TERM, e.IS_QUESTIONNAIRES_REQ, e.REFERANCE_NUMBER, e.STATUS, e.SUBMISSION_VALIDITY_DAYS, e.TENANT_ID, e.CURRENCY_ID, e.COST_CENTER, e.BUSINESS_UNIT_ID, e.CREATED_BY, e.DELIVERY_ADDRESS, e.EVENT_OWNER, e.EVENT_CATEGORY, e.MODIFIED_BY, e.PARTICIPATION_FEE_CURRENCY, e.TEMPLATE_ID, e.IS_BQ_COMPLETED, e.IS_CQ_COMPLETED, e.IS_DOCUMENT_COMPLETED, e.IS_ENVELOP_COMPLETED, e.IS_EVENT_DETAIL_COMPLETED, e.IS_MEETINGS_COMPLETED, e.IS_SUMMARY_COMPLETED, e.IS_SUPPLIER_COMPLETED, e.ACTION_DATE, e.ACTION_BY,  e.SUSPENSION_TYPE, 'Request for Tender' as EVENT_TYPE ,e.IS_AWARDED ,e.ERP_DOC_NO ,e.VIEW_SUPPLIER_NAME,e.ALLOW_CLOSE_ENVELOPE,e.ALLOW_ADD_SUPPLIER,e.ALLOW_TO_SUSPEND_EVENT,e.PREVIOUS_REQUEST,e.DEPOSIT,e.DEPOSIT_CURRENCY,e.DISABLE_MASKING,e.UNMASKED_BY,e.INTERNAL_REMARKS,e.MINIMUM_SUPPLIER_RATING,e.MAXIMUM_SUPPLIER_RATING,e.EVENT_PUSH_DATE, e.AWARD_DATE   FROM PROC_RFT_EVENTS e ";  
			view += " UNION  ";
			view += " SELECT e.ID,e.CONCLUDE_BY, e.IS_ERP_ENABLE, e.DELIVERY_DATE,e.CONCLUDE_DATE, e.URGENT_EVENT, e.START_MESSAGE_SENT, e.SUSPEND_REMARKS, e.CANCEL_REASON, e.PREVIOUS_EVENT, e.NEXT_EVENT, e.PREVIOUS_EVENT_TYPE, e.NEXT_EVENT_TYPE, e.CONCLUDE_REMARKS, e.IS_BILLOFQUANTITY_REQ, e.BUDGET_AMOUNT, e.CREATED_DATE, e.BUYER_SET_DECIMAL, e.IS_DOCUMENT_REQ, e.EVENT_DESCRIPTION, e.EVENT_END, e.EVENT_ID, e.EVENT_NAME, e.EVENT_PUBLISH_DATE, e.EVENT_START, e.EVENT_VISIBILITY, e.HISTORICAL_AMOUNT, e.IS_MEETINGS_REQ, e.MODIFIED_DATE, e.PARTICIPATION_FEES, e.PAYMENT_TERM, e.IS_QUESTIONNAIRES_REQ, e.REFERANCE_NUMBER, e.STATUS, e.SUBMISSION_VALIDITY_DAYS, e.TENANT_ID, e.CURRENCY_ID, e.COST_CENTER, e.BUSINESS_UNIT_ID, e.CREATED_BY, e.DELIVERY_ADDRESS, e.EVENT_OWNER, e.EVENT_CATEGORY, e.MODIFIED_BY, e.PARTICIPATION_FEE_CURRENCY, e.TEMPLATE_ID, e.IS_BQ_COMPLETED, e.IS_CQ_COMPLETED, e.IS_DOCUMENT_COMPLETED, e.IS_ENVELOP_COMPLETED, e.IS_EVENT_DETAIL_COMPLETED, e.IS_MEETINGS_COMPLETED, e.IS_SUMMARY_COMPLETED, e.IS_SUPPLIER_COMPLETED, e.ACTION_DATE, e.ACTION_BY,  e.SUSPENSION_TYPE, 'Request for Proposal' as EVENT_TYPE ,e.IS_AWARDED ,e.ERP_DOC_NO ,e.VIEW_SUPPLIER_NAME,e.ALLOW_CLOSE_ENVELOPE,e.ALLOW_ADD_SUPPLIER,e.ALLOW_TO_SUSPEND_EVENT,e.PREVIOUS_REQUEST,e.DEPOSIT,e.DEPOSIT_CURRENCY,e.DISABLE_MASKING ,e.UNMASKED_BY,e.INTERNAL_REMARKS,e.MINIMUM_SUPPLIER_RATING,e.MAXIMUM_SUPPLIER_RATING,e.EVENT_PUSH_DATE,e.AWARD_DATE  FROM PROC_RFP_EVENTS  e ";
			view += " UNION  ";
			view += " SELECT e.ID,e.CONCLUDE_BY, e.IS_ERP_ENABLE, e.DELIVERY_DATE,e.CONCLUDE_DATE, e.URGENT_EVENT, e.START_MESSAGE_SENT, e.SUSPEND_REMARKS, e.CANCEL_REASON, e.PREVIOUS_EVENT, e.NEXT_EVENT, e.PREVIOUS_EVENT_TYPE, e.NEXT_EVENT_TYPE, e.CONCLUDE_REMARKS, e.IS_BILLOFQUANTITY_REQ, e.BUDGET_AMOUNT, e.CREATED_DATE, e.BUYER_SET_DECIMAL, e.IS_DOCUMENT_REQ, e.EVENT_DESCRIPTION, e.EVENT_END, e.EVENT_ID, e.EVENT_NAME, e.EVENT_PUBLISH_DATE, e.EVENT_START, e.EVENT_VISIBILITY, e.HISTORICAL_AMOUNT, e.IS_MEETINGS_REQ, e.MODIFIED_DATE, e.PARTICIPATION_FEES, e.PAYMENT_TERM, e.IS_QUESTIONNAIRES_REQ, e.REFERANCE_NUMBER, e.STATUS, e.SUBMISSION_VALIDITY_DAYS, e.TENANT_ID, e.CURRENCY_ID, e.COST_CENTER, e.BUSINESS_UNIT_ID, e.CREATED_BY, e.DELIVERY_ADDRESS, e.EVENT_OWNER, e.EVENT_CATEGORY, e.MODIFIED_BY, e.PARTICIPATION_FEE_CURRENCY, e.TEMPLATE_ID, e.IS_BQ_COMPLETED, e.IS_CQ_COMPLETED, e.IS_DOCUMENT_COMPLETED, e.IS_ENVELOP_COMPLETED, e.IS_EVENT_DETAIL_COMPLETED, e.IS_MEETINGS_COMPLETED, e.IS_SUMMARY_COMPLETED, e.IS_SUPPLIER_COMPLETED, e.ACTION_DATE, e.ACTION_BY,  e.SUSPENSION_TYPE, 'Request for Quotation' as EVENT_TYPE,e.IS_AWARDED ,e.ERP_DOC_NO ,e.VIEW_SUPPLIER_NAME,e.ALLOW_CLOSE_ENVELOPE,e.ALLOW_ADD_SUPPLIER,e.ALLOW_TO_SUSPEND_EVENT,e.PREVIOUS_REQUEST,e.DEPOSIT,e.DEPOSIT_CURRENCY,e.DISABLE_MASKING ,e.UNMASKED_BY,e.INTERNAL_REMARKS,e.MINIMUM_SUPPLIER_RATING,e.MAXIMUM_SUPPLIER_RATING,e.EVENT_PUSH_DATE,e.AWARD_DATE  FROM PROC_RFQ_EVENTS  e ";
			view += " UNION  ";
			view += " SELECT e.ID,e.CONCLUDE_BY, e.IS_ERP_ENABLE, e.DELIVERY_DATE,e.CONCLUDE_DATE, e.URGENT_EVENT, e.START_MESSAGE_SENT, e.SUSPEND_REMARKS, e.CANCEL_REASON, e.PREVIOUS_EVENT, e.NEXT_EVENT, e.PREVIOUS_EVENT_TYPE, e.NEXT_EVENT_TYPE, e.CONCLUDE_REMARKS, e.IS_BILLOFQUANTITY_REQ, e.BUDGET_AMOUNT, e.CREATED_DATE, e.BUYER_SET_DECIMAL, e.IS_DOCUMENT_REQ, e.EVENT_DESCRIPTION, e.EVENT_END, e.EVENT_ID, e.EVENT_NAME, e.EVENT_PUBLISH_DATE, e.EVENT_START, e.EVENT_VISIBILITY, e.HISTORICAL_AMOUNT, e.IS_MEETINGS_REQ, e.MODIFIED_DATE, e.PARTICIPATION_FEES, e.PAYMENT_TERM, e.IS_QUESTIONNAIRES_REQ, e.REFERANCE_NUMBER, e.STATUS, e.SUBMISSION_VALIDITY_DAYS, e.TENANT_ID, e.CURRENCY_ID, e.COST_CENTER, e.BUSINESS_UNIT_ID, e.CREATED_BY, e.DELIVERY_ADDRESS, e.EVENT_OWNER, e.EVENT_CATEGORY, e.MODIFIED_BY, e.PARTICIPATION_FEE_CURRENCY, e.TEMPLATE_ID, e.IS_BQ_COMPLETED, e.IS_CQ_COMPLETED, e.IS_DOCUMENT_COMPLETED, e.IS_ENVELOP_COMPLETED, e.IS_EVENT_DETAIL_COMPLETED, e.IS_MEETINGS_COMPLETED, e.IS_SUMMARY_COMPLETED, e.IS_SUPPLIER_COMPLETED, e.ACTION_DATE, e.ACTION_BY,  e.SUSPENSION_TYPE, 'Request for Auction' as EVENT_TYPE ,e.IS_AWARDED ,e.ERP_DOC_NO ,e.VIEW_SUPPLIER_NAME,e.ALLOW_CLOSE_ENVELOPE,e.ALLOW_ADD_SUPPLIER,e.ALLOW_TO_SUSPEND_EVENT,e.PREVIOUS_REQUEST,e.DEPOSIT,e.DEPOSIT_CURRENCY,e.DISABLE_MASKING,e.UNMASKED_BY,e.INTERNAL_REMARKS,e.MINIMUM_SUPPLIER_RATING,e.MAXIMUM_SUPPLIER_RATING,e.EVENT_PUSH_DATE,e.AWARD_DATE   FROM PROC_RFA_EVENTS  e ";
			 
			query = getEntityManager().createNativeQuery(view);
			query.executeUpdate();
			
			// view = "CREATE OR REPLACE VIEW PROC_RFX_EVENTS_ACCESS AS ";
			// view += "SELECT distinct e.ID, e.IS_BILLOFQUANTITY_REQ, e.BUDGET_AMOUNT, e.CREATED_DATE,
			// e.BUYER_SET_DECIMAL, e.IS_DOCUMENT_REQ, e.EVENT_DESCRIPTION, e.EVENT_END, e.EVENT_ID, e.EVENT_NAME,
			// e.EVENT_PUBLISH_DATE, e.EVENT_START, e.EVENT_VISIBILITY, e.HISTORICAL_AMOUNT, e.IS_MEETINGS_REQ,
			// e.MODIFIED_DATE, e.PARTICIPATION_FEES, e.PAYMENT_TERM, e.IS_QUESTIONNAIRES_REQ, e.REFERANCE_NUMBER,
			// e.STATUS, e.SUBMISSION_VALIDITY_DAYS, e.TENANT_ID, e.CURRENCY_ID, e.COST_CENTER, e.CREATED_BY,
			// e.DELIVERY_ADDRESS, e.EVENT_OWNER, e.EVENT_CATEGORY, e.MODIFIED_BY, e.PARTICIPATION_FEE_CURRENCY,
			// e.TEMPLATE_ID, e.IS_BQ_COMPLETED, e.IS_CQ_COMPLETED, e.IS_DOCUMENT_COMPLETED, e.IS_ENVELOP_COMPLETED,
			// e.IS_EVENT_DETAIL_COMPLETED, e.IS_MEETINGS_COMPLETED, e.IS_SUMMARY_COMPLETED, e.IS_SUPPLIER_COMPLETED,
			// e.ACTION_DATE, e.ACTION_BY,";
			// view += " s.SUPPLIER_ID, s.IS_BID_SUBMITTED, s.SUPPLIER_EVENT_READ_TIME, s.SUPPLIER_INVITED_TIME,
			// s.SUPPLIER_BID_SUBMITTED_TIME, e.SUSPENSION_TYPE, 'Request for Information' as EVENT_TYPE ";
			// view += " FROM PROC_RFT_EVENTS e left outer join PROC_RFT_EVENT_SUPPLIERS s on e.ID = s.EVENT_ID left
			// outer join PROC_RFT_ENVELOP en on en.EVENT_ID = e.ID left outer join PROC_RFT_TEAM tm on tm.EVENT_ID =
			// e.ID left outer join PROC_RFT_ENV_EVAL evl on evl.ENVELOPE_ID = en.ID left outer join
			// PROC_RFT_EVENT_APPROVAL app on app.EVENT_ID = e.ID left outer join PROC_RFT_APPROVAL_USER usr on
			// usr.RFT_EVENT_APPROVAL_ID = app.ID";
			// view += " where en.ENVELOP_OPENER = :userId or en.LEAD_EVALUATER = :userId or tm.USER_ID = :userId or
			// evl.USER_ID = :userId or e.EVENT_OWNER = :userId or usr.USER_ID = :userId";
			// view += " UNION";
			// view += " SELECT distinct e.ID, e.IS_BILLOFQUANTITY_REQ, e.BUDGET_AMOUNT, e.CREATED_DATE,
			// e.BUYER_SET_DECIMAL, e.IS_DOCUMENT_REQ, e.EVENT_DESCRIPTION, e.EVENT_END, e.EVENT_ID, e.EVENT_NAME,
			// e.EVENT_PUBLISH_DATE, e.EVENT_START, e.EVENT_VISIBILITY, e.HISTORICAL_AMOUNT, e.IS_MEETINGS_REQ,
			// e.MODIFIED_DATE, e.PARTICIPATION_FEES, e.PAYMENT_TERM, e.IS_QUESTIONNAIRES_REQ, e.REFERANCE_NUMBER,
			// e.STATUS, e.SUBMISSION_VALIDITY_DAYS, e.TENANT_ID, e.CURRENCY_ID, e.COST_CENTER, e.CREATED_BY,
			// e.DELIVERY_ADDRESS, e.EVENT_OWNER, e.EVENT_CATEGORY, e.MODIFIED_BY, e.PARTICIPATION_FEE_CURRENCY,
			// e.TEMPLATE_ID, e.IS_BQ_COMPLETED, e.IS_CQ_COMPLETED, e.IS_DOCUMENT_COMPLETED, e.IS_ENVELOP_COMPLETED,
			// e.IS_EVENT_DETAIL_COMPLETED, e.IS_MEETINGS_COMPLETED, e.IS_SUMMARY_COMPLETED, e.IS_SUPPLIER_COMPLETED,
			// e.ACTION_DATE, e.ACTION_BY,";
			// view += " s.SUPPLIER_ID, s.IS_BID_SUBMITTED, s.SUPPLIER_EVENT_READ_TIME, s.SUPPLIER_INVITED_TIME,
			// s.SUPPLIER_BID_SUBMITTED_TIME, e.SUSPENSION_TYPE, 'Request for Information' as EVENT_TYPE ";
			// view += " FROM PROC_RFP_EVENTS e left outer join PROC_RFP_EVENT_SUPPLIERS s on e.ID = s.EVENT_ID left
			// outer join PROC_RFP_ENVELOP en on en.EVENT_ID = e.ID left outer join PROC_RFP_TEAM tm on tm.EVENT_ID =
			// e.ID left outer join PROC_RFP_ENV_EVAL evl on evl.ENVELOPE_ID = en.ID left outer join
			// PROC_RFP_EVENT_APPROVAL app on app.EVENT_ID = e.ID left outer join PROC_RFP_APPROVAL_USER usr on
			// usr.RFP_EVENT_APPROVAL_ID = app.ID";
			// view += " where en.ENVELOP_OPENER = :userId or en.LEAD_EVALUATER = :userId or tm.USER_ID = :userId or
			// evl.USER_ID = :userId or e.EVENT_OWNER = :userId or usr.USER_ID = :userId";
			// view += " UNION";
			// view += " SELECT distinct e.ID, e.IS_BILLOFQUANTITY_REQ, e.BUDGET_AMOUNT, e.CREATED_DATE,
			// e.BUYER_SET_DECIMAL, e.IS_DOCUMENT_REQ, e.EVENT_DESCRIPTION, e.EVENT_END, e.EVENT_ID, e.EVENT_NAME,
			// e.EVENT_PUBLISH_DATE, e.EVENT_START, e.EVENT_VISIBILITY, e.HISTORICAL_AMOUNT, e.IS_MEETINGS_REQ,
			// e.MODIFIED_DATE, e.PARTICIPATION_FEES, e.PAYMENT_TERM, e.IS_QUESTIONNAIRES_REQ, e.REFERANCE_NUMBER,
			// e.STATUS, e.SUBMISSION_VALIDITY_DAYS, e.TENANT_ID, e.CURRENCY_ID, e.COST_CENTER, e.CREATED_BY,
			// e.DELIVERY_ADDRESS, e.EVENT_OWNER, e.EVENT_CATEGORY, e.MODIFIED_BY, e.PARTICIPATION_FEE_CURRENCY,
			// e.TEMPLATE_ID, e.IS_BQ_COMPLETED, e.IS_CQ_COMPLETED, e.IS_DOCUMENT_COMPLETED, e.IS_ENVELOP_COMPLETED,
			// e.IS_EVENT_DETAIL_COMPLETED, e.IS_MEETINGS_COMPLETED, e.IS_SUMMARY_COMPLETED, e.IS_SUPPLIER_COMPLETED,
			// e.ACTION_DATE, e.ACTION_BY,";
			// view += " s.SUPPLIER_ID, s.IS_BID_SUBMITTED, s.SUPPLIER_EVENT_READ_TIME, s.SUPPLIER_INVITED_TIME,
			// s.SUPPLIER_BID_SUBMITTED_TIME, e.SUSPENSION_TYPE, 'Request for Information' as EVENT_TYPE ";
			// view += " FROM PROC_RFI_EVENTS e left outer join PROC_RFI_EVENT_SUPPLIERS s on e.ID = s.EVENT_ID left
			// outer join PROC_RFI_ENVELOP en on en.EVENT_ID = e.ID left outer join PROC_RFI_TEAM tm on tm.EVENT_ID =
			// e.ID left outer join PROC_RFI_ENV_EVAL evl on evl.ENVELOPE_ID = en.ID left outer join
			// PROC_RFI_EVENT_APPROVAL app on app.EVENT_ID = e.ID left outer join PROC_RFI_APPROVAL_USER usr on
			// usr.RFI_EVENT_APPROVAL_ID = app.ID";
			// view += " where en.ENVELOP_OPENER = :userId or en.LEAD_EVALUATER = :userId or tm.USER_ID = :userId or
			// evl.USER_ID = :userId or e.EVENT_OWNER = :userId or usr.USER_ID = :userId";
			// view += " UNION";
			// view += " SELECT distinct e.ID, e.IS_BILLOFQUANTITY_REQ, e.BUDGET_AMOUNT, e.CREATED_DATE,
			// e.BUYER_SET_DECIMAL, e.IS_DOCUMENT_REQ, e.EVENT_DESCRIPTION, e.EVENT_END, e.EVENT_ID, e.EVENT_NAME,
			// e.EVENT_PUBLISH_DATE, e.EVENT_START, e.EVENT_VISIBILITY, e.HISTORICAL_AMOUNT, e.IS_MEETINGS_REQ,
			// e.MODIFIED_DATE, e.PARTICIPATION_FEES, e.PAYMENT_TERM, e.IS_QUESTIONNAIRES_REQ, e.REFERANCE_NUMBER,
			// e.STATUS, e.SUBMISSION_VALIDITY_DAYS, e.TENANT_ID, e.CURRENCY_ID, e.COST_CENTER, e.CREATED_BY,
			// e.DELIVERY_ADDRESS, e.EVENT_OWNER, e.EVENT_CATEGORY, e.MODIFIED_BY, e.PARTICIPATION_FEE_CURRENCY,
			// e.TEMPLATE_ID, e.IS_BQ_COMPLETED, e.IS_CQ_COMPLETED, e.IS_DOCUMENT_COMPLETED, e.IS_ENVELOP_COMPLETED,
			// e.IS_EVENT_DETAIL_COMPLETED, e.IS_MEETINGS_COMPLETED, e.IS_SUMMARY_COMPLETED, e.IS_SUPPLIER_COMPLETED,
			// e.ACTION_DATE, e.ACTION_BY,";
			// view += " s.SUPPLIER_ID, s.IS_BID_SUBMITTED, s.SUPPLIER_EVENT_READ_TIME, s.SUPPLIER_INVITED_TIME,
			// s.SUPPLIER_BID_SUBMITTED_TIME, e.SUSPENSION_TYPE, 'Request for Information' as EVENT_TYPE ";
			// view += " FROM PROC_RFQ_EVENTS e left outer join PROC_RFQ_EVENT_SUPPLIERS s on e.ID = s.EVENT_ID left
			// outer join PROC_RFQ_ENVELOP en on en.EVENT_ID = e.ID left outer join PROC_RFQ_TEAM tm on tm.EVENT_ID =
			// e.ID left outer join PROC_RFQ_ENV_EVAL evl on evl.ENVELOPE_ID = en.ID left outer join
			// PROC_RFQ_EVENT_APPROVAL app on app.EVENT_ID = e.ID left outer join PROC_RFQ_APPROVAL_USER usr on
			// usr.RFQ_EVENT_APPROVAL_ID = app.ID";
			// view += " where en.ENVELOP_OPENER = :userId or en.LEAD_EVALUATER = :userId or tm.USER_ID = :userId or
			// evl.USER_ID = :userId or e.EVENT_OWNER = :userId or usr.USER_ID = :userId";
			// view += " UNION";
			// view += " SELECT distinct e.ID, e.IS_BILLOFQUANTITY_REQ, e.BUDGET_AMOUNT, e.CREATED_DATE,
			// e.BUYER_SET_DECIMAL, e.IS_DOCUMENT_REQ, e.EVENT_DESCRIPTION, e.EVENT_END, e.EVENT_ID, e.EVENT_NAME,
			// e.EVENT_PUBLISH_DATE, e.EVENT_START, e.EVENT_VISIBILITY, e.HISTORICAL_AMOUNT, e.IS_MEETINGS_REQ,
			// e.MODIFIED_DATE, e.PARTICIPATION_FEES, e.PAYMENT_TERM, e.IS_QUESTIONNAIRES_REQ, e.REFERANCE_NUMBER,
			// e.STATUS, e.SUBMISSION_VALIDITY_DAYS, e.TENANT_ID, e.CURRENCY_ID, e.COST_CENTER, e.CREATED_BY,
			// e.DELIVERY_ADDRESS, e.EVENT_OWNER, e.EVENT_CATEGORY, e.MODIFIED_BY, e.PARTICIPATION_FEE_CURRENCY,
			// e.TEMPLATE_ID, e.IS_BQ_COMPLETED, e.IS_CQ_COMPLETED, e.IS_DOCUMENT_COMPLETED, e.IS_ENVELOP_COMPLETED,
			// e.IS_EVENT_DETAIL_COMPLETED, e.IS_MEETINGS_COMPLETED, e.IS_SUMMARY_COMPLETED, e.IS_SUPPLIER_COMPLETED,
			// e.ACTION_DATE, e.ACTION_BY,";
			// view += " s.SUPPLIER_ID, s.IS_BID_SUBMITTED, s.SUPPLIER_EVENT_READ_TIME, s.SUPPLIER_INVITED_TIME,
			// s.SUPPLIER_BID_SUBMITTED_TIME, e.SUSPENSION_TYPE, 'Request for Information' as EVENT_TYPE ";
			// view += " FROM PROC_RFA_EVENTS e left outer join PROC_RFA_EVENT_SUPPLIERS s on e.ID = s.EVENT_ID left
			// outer join PROC_RFA_ENVELOP en on en.EVENT_ID = e.ID left outer join PROC_RFA_TEAM tm on tm.EVENT_ID =
			// e.ID left outer join PROC_RFA_ENV_EVAL evl on evl.ENVELOPE_ID = en.ID left outer join
			// PROC_RFA_EVENT_APPROVAL app on app.EVENT_ID = e.ID left outer join PROC_RFA_APPROVAL_USER usr on
			// usr.RFA_EVENT_APPROVAL_ID = app.ID";
			// view += " where en.ENVELOP_OPENER = :userId or en.LEAD_EVALUATER = :userId or tm.USER_ID = :userId or
			// evl.USER_ID = :userId or e.EVENT_OWNER = :userId or usr.USER_ID = :userId";
			//
			// query = getEntityManager().createNativeQuery(view);
			// query.executeUpdate();
		} catch (Exception e) {
			LOG.error("Error creating view : " + e.getMessage(), e);
		}
	}

}
